/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakar1;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Fransdhinta PC
 */
public class SistemPakar1Form extends javax.swing.JFrame {
    
    int a = 0;
    int b = 0;
    int c = 0;
    int d = 0;
    int e = 0;
    
    GridBagLayout layout = new GridBagLayout();
    qPanel1 p1;
    qPanel2 p2;
    qPanel3 p3;
    qPanel4 p4;
    qPanel5 p5;
    qPanel6 p6;
    
    /**
     * Creates new form SistemPakar1Form
     */
    public SistemPakar1Form() {
        initComponents();
        
        p1 = new qPanel1();
        p2 = new qPanel2();
        p3 = new qPanel3();
        p4 = new qPanel4();
        p5 = new qPanel5();
        p6 = new qPanel6();
        
        questPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p1,c);
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p2,c);
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p3,c);
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p4,c);
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p5,c);
        
        c.gridx = 0;
        c.gridy = 0;
        questPanel.add(p6,c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }
        
        
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaOrang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        lihatButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jenisKel1 = new javax.swing.JRadioButton();
        jenisKel2 = new javax.swing.JRadioButton();
        exitButton = new javax.swing.JButton();
        questPanel = new javax.swing.JPanel();
        tidak = new javax.swing.JButton();
        ya = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel1.setText("Sistem Pakar");

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel2.setText("Nama Pengguna");

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel3.setText("Ciri - Ciri");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel4.setText("Hasil");

        hasil.setEditable(false);
        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );

        lihatButton.setText("Lihat");
        lihatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jenisKel1.setText("Laki - laki");
        jenisKel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKel1ActionPerformed(evt);
            }
        });

        jenisKel2.setText("Perempuan");
        jenisKel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKel2ActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questPanelLayout = new javax.swing.GroupLayout(questPanel);
        questPanel.setLayout(questPanelLayout);
        questPanelLayout.setHorizontalGroup(
            questPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        questPanelLayout.setVerticalGroup(
            questPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        tidak.setText("Tidak");
        tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakActionPerformed(evt);
            }
        });

        ya.setText("Ya");
        ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(resetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namaOrang)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jenisKel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jenisKel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(tidak))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lihatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(ya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(questPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenisKel1)
                            .addComponent(jenisKel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tidak)
                            .addComponent(ya))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetButton)
                            .addComponent(lihatButton)
                            .addComponent(exitButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jenisKel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKel2ActionPerformed
        if (jenisKel2.isSelected())
        {
            jenisKel1.setSelected(false);
        }
    }//GEN-LAST:event_jenisKel2ActionPerformed

    private void jenisKel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKel1ActionPerformed
        if (jenisKel1.isSelected())
        {
            jenisKel2.setSelected(false);
        }
    }//GEN-LAST:event_jenisKel1ActionPerformed

    private void lihatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatButtonActionPerformed
         
        if (p6.isVisible()) {
            String nama = namaOrang.getText();
            String jenisKel = null;

            if (jenisKel1.isSelected())
            {
                jenisKel = jenisKel1.getText();
            }
            else if (jenisKel2.isSelected())
            {
                jenisKel = jenisKel2.getText();
            }
            
            //1
            if (a == 1) 
            {
                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                +"Keterangan\t:\n"
                                + "Anda berpotensi terkena sakit gigi.\n"
                                + "Lebih Baik anda Kurangi Makan Permen."
                            );
                if (b == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena sakit gigi.\n"
                                    + "Lebih Baik anda Kurangi Makanan Manis."
                                );
                    if (c == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Diabetes.\n"
                                        + "Lebih Baik anda Kurangi Makanan Manis \n"
                                        + "dan Rajinlah Berolahraga."
                                    );
                        if (d == 1) 
                        {
                            hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                            +"Keterangan\t:\n"
                                            + "Anda berpotensi terkena beberapa gangguan \n"
                                            + "Kesehatan, Aturlah Pola Makan \n"
                                            + "dan Rajinlah Berolahraga."
                                        );
                            if (e == 1) 
                            {
                                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                                +"Keterangan\t:\n"
                                                + "Anda berpotensi terkena banyak gangguan \n"
                                                + "Kesehatan, Beralihlah ke Pola Makan Sehat \n"
                                                + "dan Rajinlah Berolahraga."
                                            );
                            }
                        }
                        else if (e == 1) 
                        {
                            hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                            +"Keterangan\t:\n"
                                            + "Anda berpotensi terkena Diabetes dan \n"
                                            + "Obesitas, Aturlah Pola Makan \n"
                                            + "dan Rajinlah Berolahraga."
                                        );
                        }
                    }
                    else if (d == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Sakit gigi & perut.\n"
                                        + "Lebih Baik anda Kurangi Makanan Manis & pedas \n"
                                        + "dan Jangan lupa sikat gigi."
                                    );
                    }
                    else if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Obesitas.\n"
                                        + "Lebih Baik anda tidak makan berlebihan, \naturlah pola makan \n"
                                        + "dan Jangan lupa Berolahraga."
                                    );
                    }
                }
                else if (c == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Diabetes.\n"
                                    + "Lebih Baik anda Kurangi Makanan Manis."
                                );
                    if (d == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena beberapa gangguan \n"
                                        + "Kesehatan, Kurangi makanan tidak sehat \n"
                                        + "dan Rajinlah Berolahraga."
                                    );
                        if (e == 1) 
                        {
                            hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                            +"Keterangan\t:\n"
                                            + "Anda berpotensi terkena beberapa gangguan \n"
                                            + "Kesehatan, Aturlah Pola Makan \n"
                                            + "dan Rajinlah Berolahraga."
                                        );
                        }
                    }
                    else if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena beberapa gangguan \n"
                                        + "Kesehatan, Kurangi makanan manis \n"
                                        + "dan Beralih ke pola makan sehat."
                                    );
                    }
                }
                else if (d == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Kurangi makanan Manis dan Pedas.\n"
                                    + "Lebih baik makan dan minum yang Sehat saja."
                                );
                    if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Obesitas,\n"
                                        + "Jangan Makan Berlebihan, kurangi makanan manis & pedas.\n"
                                        + "Lebih baik makan dan minum yang Sehat saja."
                                    );
                    }
                }
                else if (e == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Kurangi makanan Manis dan Jangan Makan Berlebihan.\n"
                                    + "Karena Berpotensi membahayakan tubuh."
                                );
                }
            }
            
            //2
            else if (b == 1) 
            {
                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                +"Keterangan\t:\n"
                                + "Anda berpotensi terkena sakit gigi.\n"
                                + "Lebih Baik anda Kurangi Makan Coklat.\n"
                                + "Tetapi Coklat juga baik untuk kesehatan\n"
                                + "Jika dikonsumsi secara teratur."
                            );
                if (c == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Diabetes dan Obesitas.\n"
                                    + "Jika mengkonsumsi makanan manis secara berlebihan."
                                );
                    if (d == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Diabetes,\n"
                                        + "kurangi makanan manis.\n"
                                        + "Dan jangan terlalu sering mengkonsumsi.\n"
                                        + "Makanan Pedas agar pencernaan sehat."
                                    );
                        if (e == 1) 
                        {
                            hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                            +"Keterangan\t:\n"
                                            + "Anda berpotensi terkena beberapa gangguan kesehatan,\n"
                                            + "kurangi makanan tidak sehat.\n"
                                            + "Dan ubahlah pola makan menjadi pola makan sehat.\n"
                                            + "Perbanyak olahraga."
                                        );
                        }
                    }
                    else if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Obesitas,\n"
                                        + "kurangi makanan manis dan jangan makan berlebihan.\n"
                                        + "jangan terlalu sering mengkonsumsi.\n"
                                        + "Makanan Pedas agar pencernaan sehat,"
                                        + "Serta rajinlah berolahraga."
                                    );
                    }
                }
                else if (d == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Diabetes dan gangguan pencernaan.\n"
                                    + "Jika mengkonsumsi makanan manis & pedas secara berlebihan."
                                );
                    if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Diabetes dan gangguan pencernaan.\n"
                                        + "Jika mengkonsumsi makanan manis & pedas secara berlebihan.\n"
                                        + "Berolahragalah secara teratur."
                                    );
                    }
                }
                else if (e == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Diabetes dan Obesitas.\n"
                                    + "Jangan mengkonsumsi makanan manis berlebihan, \n"
                                    + "Serta Berolahragalah secara teratur."
                                );
                }
            }
            
            //3
            else if (c == 1) 
            {
                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                +"Keterangan\t:\n"
                                + "Anda berpotensi terkena Diabetes.\n"
                                + "Lebih Baik anda Kurangi konsumsi Minuman kemasan."
                            );
                if (d == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena gangguan pencernaan.\n"
                                    + "Jangan mengkonsumsi minuman kemasan berlebihan, \n"
                                    + "Serta Makanlah makanan sehat."
                                );
                    if (e == 1) 
                    {
                        hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                        +"Keterangan\t:\n"
                                        + "Anda berpotensi terkena Sakit perut dan Obesitas.\n"
                                        + "Lebih Baik anda Kurangi konsumsi Minuman kemasan dan makanan pedas.\n"
                                        + "Aturlah pola makan dan Rajin berolahraga."
                                    );
                    }
                }
                else if (e == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Obesitas.\n"
                                    + "Jangan mengkonsumsi minuman kemasan berlebihan, \n"
                                    + "Serta Aturlah pola makan dan Rutin berolahraga."
                                );
                }
            }
            
            //4
            else if (d == 1) 
            {
                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                +"Keterangan\t:\n"
                                + "Anda berpotensi terkena Sakit Perut.\n"
                                + "Kurangi makan makanan pedas dan tidak sehat\n"
                                + "Makan makanan sehat secara teratur."
                            );
                if (e == 1) 
                {
                    hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                    +"Keterangan\t:\n"
                                    + "Anda berpotensi terkena Sakit Perut.\n"
                                    + "Jangan mengkonsumsi Makanan pedas secara berlebihan, \n"
                                    + "Serta Aturlah pola makan dan Rutin berolahraga."
                                );
                }
            }
            
            //5
            else if (e == 1) 
            {
                hasil.setText("Nama\t:   "+nama+"\nJenis Kelamin\t:   "+jenisKel+"\n~~~~~~~~~~~~~~~~~~~~~~~~\n"
                                +"Keterangan\t:\n"
                                + "Anda berpotensi terkena gangguan pencernaan.\n"
                                + "Kurangi makan makanan pedas dan tidak sehat\n"
                                + "Dan Makanlah secara teratur."
                            );
            }
            
        }
        
    }//GEN-LAST:event_lihatButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        namaOrang.setText("");

        jenisKel1.setSelected(false);
        jenisKel2.setSelected(false);

        a = 0;
        b = 0;
        c = 0;
        d = 0;
        e = 0;
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        
        hasil.setText("");
        
        
        ya.setVisible(true);
        tidak.setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed
    
    
    private void yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaActionPerformed
        if (p1.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(true);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            a = a + 1;
        }
        
        else if (p2.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(true);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            b = b + 1;
        }
        
        else if (p3.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(true);
            p5.setVisible(false);
            p6.setVisible(false);
            c = c + 1;
        }
        
        else if (p4.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(true);
            p6.setVisible(false);
            d = d + 1;
        }
        
        else if (p5.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(true);
            tidak.setVisible(false);
            ya.setVisible(false);
            e = e + 1;
        }
    }//GEN-LAST:event_yaActionPerformed

    private void tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakActionPerformed
        if (p1.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(true);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
        }
        
        else if (p2.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(true);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
        }
        
        else if (p3.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(true);
            p5.setVisible(false);
            p6.setVisible(false);
        }
        
        else if (p4.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(true);
            p6.setVisible(false);
        }
        
        else if (p5.isVisible())
        {
            p1.setVisible(false);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(true);
            ya.setVisible(false);
            tidak.setVisible(false);
        }
    }//GEN-LAST:event_tidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemPakar1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemPakar1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemPakar1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemPakar1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemPakar1Form().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jenisKel1;
    private javax.swing.JRadioButton jenisKel2;
    private javax.swing.JButton lihatButton;
    private javax.swing.JTextField namaOrang;
    private java.awt.Panel panel1;
    private javax.swing.JPanel questPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton tidak;
    private javax.swing.JButton ya;
    // End of variables declaration//GEN-END:variables
}
